### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Lordreyan**
please merge it

### CODE REVIEW

**Comment by Lordreyan** [comment]
@Mohdjariullah

**Comment by Mohdjariullah** [comment]
ok

**Review by Mohdjariullah — APPROVED** [review]
good

**Comment by Lordreyan** [comment]
thnx

**Comment by Lordreyan** [comment]
hi

**Comment by Lordreyan** [comment]
plz merge

**Pull request closed without merging**
